version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  assignees:
  - franky47
  ignore:
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.1.0
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - franky47
  assignees:
  - franky47
