name: Continuous Integration

on:
  push:
    branches:
      - next
      - feature/*
      - dependabot/*
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16.x
      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --ignore-scripts
        name: Install dependencies
      - run: yarn ci
        name: Run integration tests
      - uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        name: Report code coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
